name: Nightly Release to PowerShell Gallery

on:
  workflow_dispatch:
  schedule:
  - cron: '30 3 * * *'
jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build an image
      run: |
        VERSION=$(cat ./version.txt)-nightly
        docker build --build-arg "PNP_MODULE_VERSION=$VERSION" ./docker -f ./docker/pnppowershell.dockerFile --tag ${{ secrets.DOCKER_USERNAME }}/powershell:$VERSION
    - name: Tag the image
      run: |
        VERSION=$(cat ./version.txt)-nightly
        docker image tag ${{ secrets.DOCKER_USERNAME }}/powershell:$VERSION ${{ secrets.DOCKER_USERNAME }}/powershell:nightly
    - name: Push the image
      run: |
        VERSION=$(cat ./version.txt)-nightly
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p '${{ secrets.DOCKER_PASSWORD }}'
        docker push ${{ secrets.DOCKER_USERNAME }}/powershell:$VERSION
        docker push ${{ secrets.DOCKER_USERNAME }}/powershell:nightly
