name: Nightly Release to PowerShell Gallery

on:
  workflow_dispatch:
  push: 
    branches:
      - dev
    paths:
      - 'docker/**'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build an image
      run: |
        cd dev
        ls
        VERSION=$(cat ./version.txt)
        docker build --build-arg "PNP_MODULE_VERSION=$VERSION" ./docker -f ./docker/pnppowershell-prerelease.dockerFile --tag pnp-powershell:$VERSION
