name: Publish to PowerShell Gallery

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: dev
    - name: Set required PowerShell modules
      id: psmodulecache
      uses: potatoqualitee/psmodulecache@v1
      with:
        modules-to-cache: PlatyPS
    - name: Setup PowerShell module cache
      id: cacher
      uses: actions/cache@v2
      with:
        path: $${ steps.psmodulecache.outputs.modulepath}}
        key: ${{ steps.psmodulecache.outputs.keygen }}
    - name: Build and Publish Module
      if: steps.cacher.outputs.cache-hit != 'true'
      env:
        POWERSHELLGALLERY_API_KEY: ${{ secrets.POWERSHELLGALLERY_API_KEY }}
      shell: pwsh
      run: |
        ./build/Build-Release.ps1
    - name: Add & Commit
      uses: EndBug/add-and-commit@v4.2.1
    - name: Push changes to github
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: dev
