name: Release to Docker Hub

on:
  workflow_dispatch:
  push: 
    branches:
      - dev
    paths:
      - 'docker/**'
      - '.github/workflows/release.yml'
jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and Publish All
      shell: pwsh
      run: |
        $securedPassword = ConvertTo-SecureString "${{ secrets.DOCKER_PASSWORD }}" -AsPlainText -Force
        ./docker/Publish-UnpublishedImage.ps1 PnP.PowerShell ${{ secrets.DOCKER_USERNAME }} powershell $securedPassword
