name: Release to Docker Hub

on:
  workflow_dispatch:
  push: 
    branches:
      - dev
    paths:
      - 'docker/**'
jobs:
  publish-docker:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build an image
      run: ./docker/publish.ps1
