name: Release to Docker Hub

on:
  workflow_dispatch:
  schedule:
  - cron: '30 3 * * *'
jobs:
  publish-docker-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and Publish All
      shell: pwsh
      run: |
        $securedPassword = ConvertTo-SecureString "${{ secrets.DOCKER_PASSWORD }}" -AsPlainText -Force
        ./docker/Publish-UnpublishedImage.ps1 PnP.PowerShell ${{ secrets.DOCKER_USERNAME }} powershell $securedPassword "ContainerAdministrator" $true "nanoserver-1809,nanoserver-20h2,nanoserver-ltsc2022"
  publish-docker-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and Publish All
      shell: pwsh
      run: |
        $securedPassword = ConvertTo-SecureString "${{ secrets.DOCKER_PASSWORD }}" -AsPlainText -Force
        ./docker/Publish-UnpublishedImage.ps1 PnP.PowerShell ${{ secrets.DOCKER_USERNAME }} powershell $securedPassword "root" $false "alpine-3.14,arm32v7-ubuntu-bionic"
